def branch = 'master'
def repoUrl = 'https://github.com/jenkins-ops-org/jenkins-files.git'
//def GIT_CREDENTIALS_ID = 'shagd<sgdajsgdsj'

pipeline {
    agent any
    stages {
         stage('Adding the version to the latest commit as a tag') {
            steps {
                
                withCredentials([usernamePassword(credentialsId: 'GIT_CREDENTIALS_ID', 
                                                  passwordVariable: 'GIT_PASSWORD', 
                                                  usernameVariable: 'GIT_USERNAME')]) 
                
                
                

                 
                {
                    sh "git config --global credential.username $GIT_USERNAME"
                    sh "git config --global credential.helper '!f() { echo password=$GIT_PASSWORD; }; f'"
                    sh "git tag ${BUILD_NUMBER}"
                    //sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@${repoUrl} --tag"
                    //sh "git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/nik786/jenkins-ops-org.git --tag"
                    sh "git push https://github.com/jenkins-ops-org/jenkins-files.git --tag"
                    //git push git@github.com:nik786/git-test-2.git
                    
                     //git push https://nik786:****@https://github.com/jenkins-ops-org/jenkins-files.git --tag
                    //git push https://<User Name>:<Token>@github.com/<User Name>/<Your Repository>.git

                  }
               }
              
            }
        }
    }
