pipeline {
    agent any
    stages {
        stage('Hello') {
            steps {
               script {
               if ( 97 < 99) {
               currentBuild.result = 'FAILURE'
               error("FAILED")
               }
    }
}
    }
    
    stage('Tagging') {
            steps {
                sh "echo "executing tagging stage""
                }
        }
    
    }
}
